---
version: '2'

services:
  jenkins-data:
    restart: 'no'
    container_name: jenkins-data-container
    image: jenkins:latest
    volumes:
      - /var/jenkins_home
    command: 'true'
  web:
    image: jenkins:latest
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes_from:
      - jenkins-data
