---
- name: Creates directory
  file: path=/var/jenkins state=directory

- name: Copy configs 
  copy: src="{{item}}" dest="/var/jenkins/{{item}}"
  with_items:
    - docker-compose.yml

- name: Install dependencies
  apt: 
    name={{ item }}
    state=present
    update_cache=yes
  with_items: 
    - apt-transport-https
    - ca-certificates
    - apparmor
    - python-dev
    - python-pip
    
- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pip
    - setuptools
    - docker-py
    - docker-compose

- name: Add docker apt repo
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present

- name: Import the Docker repository key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install Docker package
  apt:
    name=docker-engine
    update_cache=yes
    state=latest

- name: Start docker
  service:
    name: docker
    state: started

- name: "docker-compose up"
  command: "docker-compose up -d"
  args:
    chdir: /var/jenkins

- pause: seconds=60

- shell: docker run --rm --volumes-from jenkins-data-container jenkins:latest cat /var/jenkins_home/secrets/initialAdminPassword
  register: initialAdminPassword

- debug: msg="initialAdminPassword {{ initialAdminPassword.stdout }}"